# Generated by Django 2.2.7 on 2022-08-05 08:54

from django.db import migrations
import django_enumfield.db.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='ordersummary',
            name='is_deliver',
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=user.models.Status),
        ),
    ]
