# Generated by Django 2.2.7 on 2022-08-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_about_journey_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='description',
            field=models.TextField(default=0, max_length=300),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.OrderSummary')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Product')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media')),
                ('Journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='user.Journey')),
            ],
        ),
    ]
